-- Tasu Supabase Schema (Full Reset)
-- Run this in your Supabase SQL editor

-- ============================================
-- 1. DROP OLD TABLES (from previous version)
-- ============================================
drop table if exists public.blog_posts cascade;
drop table if exists public.ac_list cascade;
drop table if exists public.ph_list cascade;
drop table if exists public.cat_list cascade;

-- ============================================
-- 2. RENAME growth_posts → knowledge
-- ============================================
alter table if exists public.growth_posts rename to knowledge;

-- ============================================
-- 3. DROP OLD profiles (incompatible schema)
-- ============================================
drop table if exists public.profiles cascade;
drop table if exists public.integrations cascade;
drop table if exists public.reports cascade;

-- ============================================
-- 4. CREATE NEW TABLES
-- ============================================

-- Profiles table (linked to auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  website_url text,
  business_context text,
  onboarded boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Messages table (chat history)
create table public.messages (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

-- Integrations table (DataFast, GitHub per user)
create table public.integrations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null unique,
  datafast_api_key text,
  github_repo_url text,       -- e.g. "owner/repo" or full https URL
  github_token text,          -- optional PAT for private repos
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Reports table (AI-generated daily reports)
create table public.reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  generated_at timestamptz default now(),
  period_start timestamptz,
  period_end timestamptz,
  summary text,               -- AI-generated narrative
  suggestions jsonb,          -- [{id, text, category, done}]
  datafast_data jsonb,        -- raw DataFast snapshot
  github_data jsonb,          -- raw GitHub snapshot
  metrics jsonb               -- extracted key numbers
);

-- ============================================
-- 5. ENABLE ROW LEVEL SECURITY
-- ============================================
alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.knowledge enable row level security;
alter table public.integrations enable row level security;
alter table public.reports enable row level security;

-- ============================================
-- 6. RLS POLICIES
-- ============================================

-- Profiles: users can only access their own
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Messages: users can only access their own
create policy "Users can view own messages"
  on public.messages for select
  using (auth.uid() = user_id);

create policy "Users can insert own messages"
  on public.messages for insert
  with check (auth.uid() = user_id);

-- Knowledge: readable by all authenticated users (shared strategies)
create policy "Authenticated users can read knowledge"
  on public.knowledge for select
  using (auth.role() = 'authenticated');

-- Integrations: users own their integrations
create policy "Users own integrations"
  on public.integrations for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Reports: users own their reports
create policy "Users can view own reports"
  on public.reports for select
  using (auth.uid() = user_id);

create policy "Users can insert own reports"
  on public.reports for insert
  with check (auth.uid() = user_id);

create policy "Users can update own reports"
  on public.reports for update
  using (auth.uid() = user_id);

-- Daily reports table (auto-generated by system, one per user per day)
create table public.daily_reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  date date not null default current_date,
  summary text,
  suggestions jsonb,      -- [{id, text, category, done}]
  metrics jsonb,          -- {visitors_30d, revenue_30d, conversion_rate, commits_30d}
  datafast_data jsonb,
  github_data jsonb,
  generated_at timestamptz default now(),
  unique(user_id, date)
);

-- Roadmap items (admin-managed)
create table public.roadmap_items (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  status text default 'planned' check (status in ('planned', 'in_progress', 'done')),
  category text,
  vote_count integer default 0,
  sort_order integer default 0,
  created_at timestamptz default now()
);

-- Roadmap votes (one per user per item)
create table public.roadmap_votes (
  id uuid default gen_random_uuid() primary key,
  item_id uuid references public.roadmap_items on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamptz default now(),
  unique(item_id, user_id)
);

-- ============================================
-- 7. ENABLE RLS ON NEW TABLES
-- ============================================
alter table public.daily_reports enable row level security;
alter table public.roadmap_items enable row level security;
alter table public.roadmap_votes enable row level security;

-- daily_reports policies
create policy "Users can view own daily reports"
  on public.daily_reports for select
  using (auth.uid() = user_id);

create policy "Users can update own daily reports"
  on public.daily_reports for update
  using (auth.uid() = user_id);

-- roadmap_items: readable by all authenticated users
create policy "Authenticated users can read roadmap items"
  on public.roadmap_items for select
  using (auth.role() = 'authenticated');

-- roadmap_votes: users own their votes
create policy "Users can view all votes"
  on public.roadmap_votes for select
  using (auth.role() = 'authenticated');

create policy "Users can insert own vote"
  on public.roadmap_votes for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own vote"
  on public.roadmap_votes for delete
  using (auth.uid() = user_id);

-- ============================================
-- 8. INDEXES
-- ============================================
create index if not exists idx_messages_user_id on public.messages(user_id);
create index if not exists idx_messages_created_at on public.messages(created_at);
create index if not exists idx_knowledge_type on public.knowledge(type);
create index if not exists idx_reports_user_id on public.reports(user_id);
create index if not exists idx_reports_generated_at on public.reports(generated_at desc);
create index if not exists idx_daily_reports_user_id on public.daily_reports(user_id);
create index if not exists idx_daily_reports_date on public.daily_reports(date desc);
create index if not exists idx_roadmap_votes_item_id on public.roadmap_votes(item_id);
create index if not exists idx_roadmap_votes_user_id on public.roadmap_votes(user_id);

-- ============================================
-- 9. DATA SNAPSHOTS (raw daily data from providers)
-- ============================================
-- Provider-agnostic: "datafast", "stripe", "posthog", etc.
create table public.data_snapshots (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  provider text not null,          -- "datafast", "github", "stripe", "posthog"
  date date not null default current_date,
  raw_data jsonb not null,         -- full API response stored as-is
  collected_at timestamptz default now(),
  unique(user_id, provider, date)
);

alter table public.data_snapshots enable row level security;

create policy "Users can view own snapshots"
  on public.data_snapshots for select
  using (auth.uid() = user_id);

create policy "Service can insert snapshots"
  on public.data_snapshots for insert
  with check (auth.uid() = user_id);

create index if not exists idx_data_snapshots_user_provider on public.data_snapshots(user_id, provider);
create index if not exists idx_data_snapshots_date on public.data_snapshots(date desc);

-- ============================================
-- 10. TASKS (from chat + reports)
-- ============================================
create table public.tasks (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  content text not null,
  done boolean default false,
  pinned boolean default true,
  source text default 'chat',      -- "chat", "report"
  source_id text,                  -- message_id or report_id that created it
  created_at timestamptz default now(),
  completed_at timestamptz
);

alter table public.tasks enable row level security;

create policy "Users own tasks"
  on public.tasks for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_tasks_user_id on public.tasks(user_id);
create index if not exists idx_tasks_done on public.tasks(user_id, done);

-- ============================================
-- 11. INTEGRATION REQUESTS (user wants a new integration)
-- ============================================
create table public.integration_requests (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  tool_name text not null,         -- e.g. "stripe", "posthog", "plausible"
  details text,
  created_at timestamptz default now()
);

alter table public.integration_requests enable row level security;

create policy "Users can insert own integration requests"
  on public.integration_requests for insert
  with check (auth.uid() = user_id);

create policy "Users can view own integration requests"
  on public.integration_requests for select
  using (auth.uid() = user_id);

-- ============================================
-- 12. ADD self_reported_mrr TO PROFILES
-- ============================================
alter table public.profiles add column if not exists self_reported_mrr integer;
